Update documentation
idahogurl/vs-code-prettier-eslint pull request #48
Opened 2022-07-18 15:44 UTC by mattbrannon

This PR attempts to simplify the process of setting up a new project with the `vs-code-prettier-eslint` extension. Changes to the `README.md` include the following:

- A general restructuring of the document. 
    - The example projects and troubleshooting sections are moved to the end of the document. 
    - The installation and setup sections are moved to the beginning
- The sections detailing installation and setup and have been mostly rewritten.

Moving the troubleshooting and examples sections to the end and the installation section to the beginning allows the reader to read from top to bottom without as much jumping back and forth between sections.  

The goal of the rewrite is help people get things installed and setup as quickly and easily as possible. Code examples are provided that users can copy/paste directly into their terminal. The section detailing setup includes a json snippet that users can paste directly into their workspace settings. A link to the troubleshooting section is also provided in case something goes wrong. 

It's quite a big change to the current documentation so please let me know what you think. Any and all feedback is welcome.

2022-07-20 15:54 UTC, idahogurl commented on README.md
> -- The [Prettier extension](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode) is not required.
This is actually important. You wouldn't think so but I had people thinking they had to have it installed.

2022-07-20 16:27 UTC, idahogurl requested changes
Thanks Matt for the PR! This does look better. The reasoning behind putting the troubleshooting and example projects first was that I got so many issues where people wouldn't even check the troubleshooting section before they created an issue. 

Could we put a TOC with some of the 2nd level headers as links (Installation, Configuration, Troubleshooting, Example Projects)

2022-07-20 16:27 UTC, idahogurl commented on README.md
> +```
```suggestion
### TypeScript Projects
```bash
yarn add -D prettier@^2.5.1 eslint@^8.7.0 @typescript-eslint/parser@^5.0.1 typescript@^4.4.4
```

### Vue Projects
```bash
yarn add -D prettier@^2.5.1 eslint@^8.7.0 vue-eslint-parser@^8.0.0
```
```

2022-07-20 16:27 UTC, idahogurl commented on README.md
> +## Install dependencies
```suggestion
## Install Dependencies
```

2022-07-20 16:27 UTC, idahogurl commented on README.md
> +You can run `eslint --print-config .eslintrc.js` to check your ESLint configuration. This prints out the configuration being used after it applies plugins & extended configurations.
```suggestion
You can run `npx eslint --print-config .eslintrc.js` to check your ESLint configuration. This prints out the configuration being used after it applies plugins & extended configurations.
```

Might as well make changes I've wanted to make for a while 🙂

2022-07-20 16:27 UTC, idahogurl commented on README.md
> +**Note**: There are known performance issues with quad-core or slower processors. The slowness comes from ESLint CLI which the 'prettier-eslint' package uses.
```suggestion
**Note**: There are known performance issues with quad-core or slower processors. The slowness comes from the 'prettier-eslint' package the extension uses.
```

Might as well make changes I've wanted to make for a while 🙂

2022-07-20 16:27 UTC, idahogurl commented on README.md
> +4. **Restart VsCode**
```suggestion
4. **Restart VS Code**  
```

2022-07-20 16:27 UTC, idahogurl commented on README.md
> +1. Open the command palette in vscode by typing:
```suggestion
1. Open the command palette in VS Code by typing:
```

This is how Microsoft abbreviates Visual Studio Code. See screenshot below.
<img width="1435" alt="Screen Shot 2022-07-20 at 10 08 53 AM" src="https://user-images.githubusercontent.com/10620169/180030856-4fcb70de-6d25-480c-8360-bb6df51efcc5.png">

2022-07-25 19:27 UTC, mattbrannon commented
@idahogurl Apologies for the late response. Those were all good suggestions.

2022-07-25 20:08 UTC, idahogurl approved these changes

2022-07-25 20:09 UTC, merged

2022-07-25 20:10 UTC, idahogurl commented
Closes #46

2022-07-29 21:42 UTC, mattbrannon commented
> Could we put a TOC with some of the 2nd level headers as links (Installation, Configuration, Troubleshooting, Example Projects)

@idahogurl I completely missed your request before submitting my final request for a review of changes. My apologies for that. I see that you implemented it yourself though. It looks great! Thanks for accepting the PR. I hope it helps reduce some of the complexity with installing and configuring everything. I love this extension. It's the default for all my personal projects. Thanks for making it and thanks for allowing me to contribute to it!

2022-08-01 23:19 UTC, idahogurl commented
@mattbrannon No worries! You did most of the heavy lifting. Thanks for the PR again.